# Generated by Django 5.0.2 on 2024-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_link',
            new_name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
